export const database = {
  pattern: {
    warning: {
      warningNotice:
        'WARNING! Better not to use this tag/attribute or use logs in source. It can lead to serious consequences for your safety.',
      warningRegex: {
        tagsOrAttr: [
          '<applet',
          '<base',
          '<basefont',
          '<dialog',
          '<embed',
          '<frameset',
          '<form',
          '<iframe',
          '<input',
          '<link',
          '<main',
          '<menuitem',
          '<noframes',
          '<noscript',
          '<object',
          '<optgroup',
          '<option',
          '<param',
          '<picture',
          '<progress',
          '<rp',
          '<rt',
          '<ruby',
          '<script',
          '<select',
          '<textarea',
          '<wbr',
          '</applet',
          '</base',
          '</basefont',
          '</dialog',
          '</embed',
          '</frameset',
          '</form',
          '</iframe',
          '</input',
          '</link',
          '</main',
          '</menuitem',
          '</noframes',
          '</noscript',
          '</object',
          '</optgroup',
          '</option',
          '</param',
          '</picture',
          '</progress',
          '</rp',
          '</rt',
          '</ruby',
          '</script',
          '</select',
          '</textarea',
          '</wbr',
          ' async',
          ' autocomplete',
          ' autofocus',
          ' autosave',
          ' bgcolor',
          ' buffered',
          ' challenge',
          ' code',
          ' codebase',
          ' content',
          ' contenteditable',
          ' contextmenu',
          ' data',
          ' data-*',
          ' default',
          ' defer',
          ' dirname',
          ' download',
          ' draggable',
          ' dropzone',
          ' formaction',
          ' hidden',
          ' high',
          ' abbr',
          ' axis',
          ' cellpadding',
          ' cellspacing',
          ' charoff',
          ' clear',
          ' compact',
          ' controlslist',
          ' frame',
          ' hreflang',
          ' hspace',
          ' id',
          ' ismap',
          ' label',
          ' lang',
          ' longdesc',
          ' loop',
          ' loopcount',
          ' loopend',
          ' loopstart',
          ' maxlength',
          ' media',
          ' method',
          ' multiple',
          ' muted',
          ' name',
          ' nohref',
          ' noshade',
          ' nowrap',
          ' poster',
          ' preload',
          ' prompt',
          ' readonly',
          ' rel',
          ' rev',
          ' rows',
          ' rowspan',
          ' rules',
          ' scope',
          ' selected',
          ' shape',
          ' size',
          ' span',
          ' src',
          ' start',
          ' style',
          ' summary',
          ' tabindex',
          ' target',
          ' title',
          ' type',
          ' usemap',
          ' valign',
          ' value',
          ' vspace',
          ' width',
          ' xml:lang',
          'console.log(',
        ],
      },
    },
    error: {
      errorNotice: 'ERROR! This code seriously compromises your security.',
      errorRegx: [
        /(^[^\/\n]*)*document.cookie/gim,
        /(^[^\/\n]*)*eval[(]+/gim,
        /(^[^\/\n]*)*require([\s]*)([(][^'"])([A-Za-z])/gim,
        /(^[^\/\n]*)*innerHTML/gim,
        /(^[^\/\n]*)*dangerouslySetInnerHTML/gim,
      ],
    },
    possibleError: {
      possibleNotice: 'POSSIBLE ERROR! Better safe than sorry.',
      possibleErrorRegex: ['Regex', 'regex'],
    },
  },
};
